# 网站基本设置
title: Yuting Wang | Bioinformatics Researcher
tagline: PhD Candidate in Biology @ Tongji University
email: 2111271@tongji.edu.cn
description: >
  A final-year PhD student specializing in single-cell transcriptomics, 
  immunosenescence, and bioinformatics data analysis. 
  Passionate about exploring the molecular mechanisms of aging and cancer therapy.
baseurl: "" # 无需修改
url: "https://Bioinfo_Wang.github.io" # 替换为你的仓库网址（即用户名.github.io）
author: Bioinfo_Wang
twitter_username: # 可选：你的Twitter账号（无则留空）
github_username: ytwang21 # 替换为你的GitHub账号名
linkedin_username: # 可选：你的领英账号（无则留空）


navbar-links:
  Home: /
  News & Events: /pages/news
  Publications: /pages/publications
  CV: "https://wppcv.readthedocs.io/en/latest/"    # 把简历放到 readthedocs 上
  

share-links-active:
  github: Bioinfo_Wang
  email: true
  # twitter: true
  # facebook: true
  # linkedin: true
  # vk: false

  
# # 网站外观设置
# theme: beautiful-jekyll
# show_downloads: false
# nav_pages:
#   - About: "about"
#   - Research: "research"
#   - Publications: "publications"
#   - Skills: "skills"
#   - Awards: "awards" 

######################################
# --- Colours / background image --- #
######################################
# Personalize the colours in your website. Colour values can be any valid CSS colour
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"  
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"


# 其他配置（无需修改）
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
